### ISSUE TITLE
Does this work with custom derives?

### ISSUE THREAD

**Issue by thomaseizinger** [ggwpez/proc-macro-warning#2]
I am trying to use this with a custom-derive and it doesn't seem to work. Here is a MRE: https://github.com/thomaseizinger/proc-macro-warning-MRE

Any ideas?

**Comment by ggwpez** [comment]
Thanks for investigating and the MRE!  
I actually observed the same thing, but did not look closer since it worked in Substrate.  

Looks like it is important to pass in a span - otherwise it wont trigger (was not actively aware of that).  
Your MRE can be fixed by putting the span of the parsed input:  
```rust
#[proc_macro_derive(MyDerive)]
pub fn my_derive(input: TokenStream) -> TokenStream {
    let input = syn::parse_macro_input!(input as syn::DeriveInput);

    let warning = proc_macro_warning::Warning::new_deprecated("test")
        .old("foo").new("bar")
        .span(input.span()) // <- here
        .build();

    quote::quote!{ #warning }.into()
}
```
produces:
![image](https://user-images.githubusercontent.com/10380170/236325360-de412c96-490e-4fba-b033-18a8a4a0ebca.png)

Please let me know if this fixes your issue. I will add an example specifically for derive macros and maybe make the `.span` call mandatory.

**Comment by thomaseizinger** [comment]
@tcoratger Mind trying this on https://github.com/libp2p/rust-libp2p/pull/3848?

**Comment by thomaseizinger** [comment]
> Thanks for investigating and the MRE!  
> I actually observed the same thing, but did not look closer since it worked in Substrate.  
> 
> Looks like it is important to pass in a span - otherwise it wont trigger (was not actively aware of that).  
> Your MRE can be fixed by putting the span of the parsed input:  
> ```rust
> #[proc_macro_derive(MyDerive)]
> pub fn my_derive(input: TokenStream) -> TokenStream {
>     let input = syn::parse_macro_input!(input as syn::DeriveInput);
> 
>     let warning = proc_macro_warning::Warning::new_deprecated("test")
>         .old("foo").new("bar")
>         .span(input.span()) // <- here
>         .build();
> 
>     quote::quote!{ #warning }.into()
> }
> ```
> produces:
> ![image](https://user-images.githubusercontent.com/10380170/236325360-de412c96-490e-4fba-b033-18a8a4a0ebca.png)
> 
> Please let me know if this fixes your issue. I will add an example specifically for derive macros and maybe make the `.span` call mandatory.

Awesome, thank you! I hope this works :)

**Comment by thomaseizinger** [comment]
Thanks! This now works.
